### ISSUE TITLE
Anaconda / MATLAB environment issues

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/umap-matlab-wrapper#4]
### What I want to do
Open MATLAB from desktop, then run `conda.setenv('umap')` from within MATLAB and set my conda environment, then run `u = umap; u.fit(D)` on some data. 
### What happens instead
MATLAB has some sort of environment issue, where it can't find any Python modules (like SciPy) that should be installed in the conda environment. The script runs fine in Python.
### Workaround
Set up your conda environment first, then run MATLAB from the same terminal
```bash
$ conda activate umap
$ matlab
```

**Comment by alec-hoyland** [comment]
```matlab
>> conda.init
>> conda.setenv('umap')
>> conda.getenv

base     /home/alec/anaconda
mkdocs     /home/alec/anaconda/envs/mkdocs
msort     /home/alec/anaconda/envs/msort
*umap     /home/alec/anaconda/envs/umap
>> u = umap

u = 

  umap with properties:

             n_neighbors: 15
            n_components: 2
                  metric: 'euclidean'
           learning_rate: 1
                min_dist: 0.1000
                  spread: 1
        set_op_mix_ratio: 1
      local_connectivity: 1
      repulsion_strength: 1
    negative_sample_rate: 5
    transform_queue_size: 4
      target_n_neighbors: -1
           target_weight: 0.5000
          transform_seed: 42
          containing_dir: '/home/alec/code/umap-matlab-wrapper'

>> u.fit(rand(100,100))
Traceback (most recent call last):
  File "/home/alec/code/umap-matlab-wrapper/run_umap.py", line 10, in <module>
    import scipy.io
ModuleNotFoundError: No module named 'scipy'
```

**Comment by sg-s** [comment]
This looks like you haven't installed the `scipy` module in your `umap` environment

**Comment by alec-hoyland** [comment]
It does, doesn't it. That's the first thing I checked.

Except that 
```bash
$ conda activate umap
$ conda list | grep scipy
```
yields
```bash
scipy                     1.2.1            py37he2b7bc3_0  
```

**Comment by alec-hoyland** [comment]
I spoke with the research computing guy for my building, and he suggested running
```bash
$ conda activate umap
$ matlab
```
in order to force MATLAB to use the `conda` environment or somesuch. This fixed the problem, though it's clearly a workaround.

1. Setting the `conda` environment in the terminal and then opening MATLAB separately causes this error.
2. Setting the `conda` environment in the terminal and opening matlab from the same terminal session solves this problem. Running `conda.getenv` in MATLAB from here shows the correct `conda` environment (e.g. `*umap     /home/alec/anaconda/envs/umap`).
3. Running 
```matlab
conda.setenv('umap')
u = umap;
u.fit(rand(100,100));
```
causes the same issue (e.g.)
```matlab
Traceback (most recent call last):
  File "/home/alec/code/umap-matlab-wrapper/run_umap.py", line 10, in <module>
    import scipy.io
ModuleNotFoundError: No module named 'scipy'
Error using umap/fit (line 29)
Failed to read output data file, does it exist?
```

**Comment by sg-s** [comment]
No, no....you have to check these environment variables **from within MATLAB**

So try

```
% in MATLAB!
! which python
! which conda
! conda env list
```

**Comment by alec-hoyland** [comment]
Okay, so here's the problem...
```matlab
>> !which python
/usr/bin/python
>> !which conda
conda not found
>> !conda env list
zsh:1: command not found: conda
```
Now let's add `condalab`
```
>> addpath ~/code/condalab/
>> conda.init
>> !which python
/home/alec/anaconda/bin/python
>> !which python
/home/alec/anaconda/bin/python
>> !which conda
/home/alec/anaconda/bin/conda
```

`condalab` works as expected. It finds the correct Python distribution.
Let's set up the environment.

```
>> conda.setenv('umap')
>> u = umap

u = 

  umap with properties:

             n_neighbors: 15
            n_components: 2
                  metric: 'euclidean'
           learning_rate: 1
                min_dist: 0.1000
                  spread: 1
        set_op_mix_ratio: 1
      local_connectivity: 1
      repulsion_strength: 1
    negative_sample_rate: 5
    transform_queue_size: 4
      target_n_neighbors: -1
           target_weight: 0.5000
          transform_seed: 42
          containing_dir: '/home/alec/code/umap-matlab-wrapper'

>> u.fit(rand(1000,1000))
Traceback (most recent call last):
  File "/home/alec/code/umap-matlab-wrapper/run_umap.py", line 10, in <module>
    import scipy.io
ModuleNotFoundError: No module named 'scipy'
Error using umap/fit (line 29)
Failed to read output data file, does it exist?
```

Okay, no luck. Let's take a closer look.

```matlab
>> conda.setenv('umap')
>> !conda env list
# conda environments:
#
base                  *  /home/alec/anaconda
mkdocs                   /home/alec/anaconda/envs/mkdocs
msort                    /home/alec/anaconda/envs/msort
umap                     /home/alec/anaconda/envs/umap

>> conda.getenv

base     /home/alec/anaconda
mkdocs     /home/alec/anaconda/envs/mkdocs
msort     /home/alec/anaconda/envs/msort
*umap     /home/alec/anaconda/envs/umap
```

So `condalab` is doing something but not changing my actual `conda` environment...?

**Comment by sg-s** [comment]
OK, now we're getting somewhere. For whatever reason, `setenv` isn't working. Interesting.

**Comment by sg-s** [comment]
what does `conda.getenv` give you?

**Comment by sg-s** [comment]
So I installed umap and condalab from scratch and have absolutely no problem using it. 

```
% conda getenv shows that I have two envs installed
conda.getenv

*base     /Users/srinivas/anaconda3
umap     /Users/srinivas/anaconda3/envs/umap
```

Now I switch to the correct env:


```
conda.setenv('umap')
```

Verifying that it has stuck:

```
conda.getenv

base     /Users/srinivas/anaconda3
*umap     /Users/srinivas/anaconda3/envs/umap

```

Now, maybe you are confused that you still see this when you do this:

```
% from within MATLAB
! conda env list
# conda environments:
#
base                  *  /Users/srinivas/anaconda3
umap                     /Users/srinivas/anaconda3/envs/umap
```

See it still says "base" is active? Well, that's because `condalab` doesn't actually do anything w.r.t conda -- it merely re-arranges things in the path so that binaries in the correct environment are used. `conda` doesn't know about `condalab`, so `conda` will think it's in whatever environment it was started in. However, everything works nicely:

```
u = umap; u.metric = 'precomputed'; R = u.fit(D);
% it works
```
