### ISSUE TITLE
Transpose data argument so that this function works the same way as MATLAB built-ins

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/umap-matlab-wrapper#5]
MATLAB built-in functions like `pca`  and `tsne` expect the data matrix argument to be an M x N matrix, where M is the number of observations and N is the number of features.

Currently, this function expects an N x M matrix. The fit function should be changed, and the crabsort plugin should be checked as well.

**Comment by alec-hoyland** [comment]
I'll take care of this tomorrow.

**Comment by sg-s** [comment]
Actually no

The syntax now is X(N_points, N_dim) 

which is both correct for matlab and for umap. Don't see the problem here

**Comment by alec-hoyland** [comment]
I fixed this a while back, I guess we forgot to close the issue.
